name       : automake
version    : 1.16.2
release    : 12
source     :
    - https://ftp.gnu.org/gnu/automake/automake-1.16.2.tar.xz : ccc459de3d710e066ab9e12d2f119bd164a08c9341ca24ba22c9adaa179eedd0
homepage   : https://www.gnu.org/software/automake/
license    : GPL-2.0-or-later
component  : system.devel
summary    : Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
description: |
    Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # enable legacy eopkg builds (non-ypkg) to reconfigure
    export main_version="1.16"
    ln -s automake-${main_version} $installdir/usr/share/gnuconfig
