name       : automake
version    : 1.16.1
release    : 11
source     :
    - https://ftp.gnu.org/gnu/automake/automake-1.16.1.tar.xz : 5d05bb38a23fd3312b10aea93840feec685bdf4a41146e78882848165d3ae921
homepage   : http://www.gnu.org/software/automake/
license    :
    - GPL-3.0
summary    : Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
component  : system.devel
description: |
    Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # enable legacy eopkg builds (non-ypkg) to reconfigure
    export main_version="1.16"
    ln -s automake-${main_version} $installdir/usr/share/gnuconfig
