name       : automake
version    : 1.16.3
release    : 13
source     :
    - https://ftp.gnu.org/gnu/automake/automake-1.16.3.tar.xz : ff2bf7656c4d1c6fdda3b8bebb21f09153a736bcba169aaf65eab25fa113bf3a
homepage   : https://www.gnu.org/software/automake/
license    : GPL-2.0-or-later
component  : system.devel
summary    : Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
description: |
    Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # enable legacy eopkg builds (non-ypkg) to reconfigure
    export main_version="1.16"
    ln -s automake-${main_version} $installdir/usr/share/gnuconfig
check      : |
    %make check
