name       : automake
version    : 1.16.5
release    : 14
source     :
    - https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.xz : f01d58cd6d9d77fbdca9eb4bbd5ead1988228fdb73d6f7a201f5f8d6b118b469
homepage   : https://www.gnu.org/software/automake/
license    : GPL-2.0-or-later
component  : system.devel
summary    : Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
description: |
    Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # enable legacy eopkg builds (non-ypkg) to reconfigure
    export main_version="1.16"
    ln -s automake-${main_version} $installdir/usr/share/gnuconfig
check      : |
    %make check
