name       : automake
version    : 1.15
release    : 8
source     :
    - https://ftp.gnu.org/gnu/automake/automake-1.15.tar.xz : 9908c75aabd49d13661d6dcb1bc382252d22cc77bf733a2d55e87f2aa2db8636
homepage   : http://www.gnu.org/software/automake/
license    :
    - GPL-3.0
summary    : Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
component  : system.devel
description: |
    Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # enable legacy eopkg builds (non-ypkg) to reconfigure
    ln -s automake-${version} $installdir/usr/share/gnuconfig
