name       : automake
version    : 1.15.1
release    : 9
source     :
    - https://ftp.gnu.org/gnu/automake/automake-1.15.1.tar.xz : af6ba39142220687c500f79b4aa2f181d9b24e4f8d8ec497cea4ba26c64bedaf
homepage   : http://www.gnu.org/software/automake/
license    :
    - GPL-3.0
summary    : Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
component  : system.devel
description: |
    Automake is a tool for automatically generating `Makefile.in' files compliant with the GNU Coding Standards
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # enable legacy eopkg builds (non-ypkg) to reconfigure
    ln -s automake-${version} $installdir/usr/share/gnuconfig
